ranking_features = [
    # 'Full name',
    # 'Race/ethnicity',
    # 'Prior connection (1)',
    # 'Prior connection (2)',
    # 'Price & affordability (1)',
    # 'Price & affordability (2)',
    # 'Price & affordability (3)',
    'Location (1)',
    'Location (2)',
    # 'Proximity to work/school',
    # 'Proximity to public transit',
    # 'Proximity to businesses',
    # 'Privacy',
    # 'Cleanliness',
    # 'Bedtime',
    # 'Smoker/non-smoker',
    # 'Pet-friendly'
]

survey_features = [
    # 'Full name',
    # 'Race/ethnicity',
    # 'College/university',
    # 'Company',
    # 'Minimum monthly rent',
    # 'Maximum monthly rent',
    # 'Actual monthly rent',
    # 'Location',
    'Latitude',
    'Longitude',
    # 'Work/school proximity',
    # 'Public transit proximity',
    # 'Local business proximity',
    # 'Privacy level',
    # 'Cleanliness level',
    # 'Bedtime',
    # 'Smoker/non-smoker',
    # 'Pet owner'
]